name: aneesh

on:
  push:
jobs:
  python_job:
    runs-on: ubantu-latest
    steps:
        -name: checkout-name
        uses: actions/checkout@v2
        -name: python-setup
        uses: actions/python-setup@v2
        with: 
            python-version: '3.x'
        -name: run python code
        run: python3 -c "print('hello code')"
        
    
      
